"use client";

import Image from "next/image";
import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";
import { useState } from "react";
import type { FormEvent } from "react";
import { toast } from "sonner";

import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Switch } from "@/components/ui/switch";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import type { CatalogService, ServiceCategory } from "@/lib/service-catalog";
import { cn } from "@/lib/utils";

export function ServiceCatalogTabs() {
  const pathname = usePathname();
  const tabs = [
    { label: "Categories", href: "/admin/services/categories" },
    { label: "Services", href: "/admin/services" },
    { label: "Pricing", href: "/admin/services/pricing" },
  ];
  return <nav className="flex gap-2 overflow-x-auto rounded border border-[#DCE6F2] bg-white p-1">{tabs.map((tab)=><Link key={tab.href} href={tab.href} className={cn("whitespace-nowrap rounded px-4 py-2 text-[12px] font-medium",pathname===tab.href?"bg-[#075DFF] text-white":"text-[#385071] hover:bg-[#F1F6FD]")}>{tab.label}</Link>)}</nav>;
}

function CatalogImage({ path, name }: { path: string; name: string }) {
  return path ? <Image src={path} alt="" width={42} height={42} className="h-10 w-10 object-contain" /> : <span className="flex h-10 w-10 items-center justify-center rounded bg-[#EEF5FF] text-[15px] font-semibold text-[#075DFF]">{name.slice(0,1)}</span>;
}

export function ServiceCategoriesAdmin({ initialCategories }: { initialCategories: ServiceCategory[] }) {
  const [categories,setCategories]=useState(initialCategories);const [saving,setSaving]=useState(false);
  async function create(event:FormEvent<HTMLFormElement>){event.preventDefault();setSaving(true);const form=new FormData(event.currentTarget);const response=await fetch("/api/admin/service-categories",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:form.get("name"),imagePath:form.get("imagePath"),displayOrder:Number(form.get("displayOrder"))})});const data=await response.json() as {category?:ServiceCategory;message?:string};setSaving(false);if(!response.ok||!data.category){toast.error(data.message??"Unable to create category");return;}setCategories(current=>[...current,data.category!].sort((a,b)=>a.displayOrder-b.displayOrder));event.currentTarget.reset();toast.success("Category created");}
  async function toggle(category:ServiceCategory){const response=await fetch(`/api/admin/service-categories/${category.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({isActive:!category.isActive})});const data=await response.json() as {category?:ServiceCategory;message?:string};if(!response.ok||!data.category){toast.error(data.message??"Unable to update category");return;}setCategories(current=>current.map(item=>item.id===category.id?data.category!:item));}
  return <div className="space-y-3"><ServiceCatalogTabs/><Card><CardHeader><CardTitle>Add Category</CardTitle></CardHeader><CardContent><form onSubmit={create} className="grid gap-3 md:grid-cols-[1fr_1fr_120px_auto]"><Input name="name" required maxLength={80} placeholder="Category name" /><Input name="imagePath" placeholder="/category-image.png" /><Input name="displayOrder" required min={0} type="number" defaultValue={categories.length+1} placeholder="Order" /><Button disabled={saving} className="bg-[#075DFF]">{saving?"Saving...":"Add Category"}</Button></form></CardContent></Card><Card><CardContent className="p-0"><Table><TableHeader><TableRow><TableHead>Image</TableHead><TableHead>Category</TableHead><TableHead>Mobile Order</TableHead><TableHead>Status</TableHead></TableRow></TableHeader><TableBody>{categories.map(category=><TableRow key={category.id}><TableCell><CatalogImage path={category.imagePath} name={category.name}/></TableCell><TableCell><p className="font-medium">{category.name}</p><p className="mt-1 text-[11px] text-[#52627A]">{category.slug}</p></TableCell><TableCell>{category.displayOrder}</TableCell><TableCell><div className="flex items-center gap-2"><Switch checked={category.isActive} onCheckedChange={()=>toggle(category)} /><span className="text-[12px]">{category.isActive?"Shown":"Hidden"}</span></div></TableCell></TableRow>)}</TableBody></Table></CardContent></Card></div>;
}

export function CatalogServicesAdmin({ initialCategories, initialServices }: { initialCategories:ServiceCategory[];initialServices:CatalogService[] }) {
  const [services,setServices]=useState(initialServices);const [saving,setSaving]=useState(false);
  async function create(event:FormEvent<HTMLFormElement>){event.preventDefault();setSaving(true);const form=new FormData(event.currentTarget);const response=await fetch("/api/admin/catalog-services",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({categoryId:form.get("categoryId"),name:form.get("name"),imagePath:form.get("imagePath"),unit:form.get("unit"),regularPrice:Number(form.get("regularPrice")),expressPrice:form.get("expressPrice"),turnaround:form.get("turnaround"),displayOrder:Number(form.get("displayOrder"))})});const data=await response.json() as {service?:CatalogService;message?:string};setSaving(false);if(!response.ok||!data.service){toast.error(data.message??"Unable to create service");return;}setServices(current=>[...current,data.service!]);event.currentTarget.reset();toast.success("Service created");}
  async function toggle(service:CatalogService){const response=await fetch(`/api/admin/catalog-services/${service.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({isActive:!service.isActive})});const data=await response.json() as {service?:CatalogService;message?:string};if(!response.ok||!data.service){toast.error(data.message??"Unable to update service");return;}setServices(current=>current.map(item=>item.id===service.id?data.service!:item));}
  return <div className="space-y-3"><ServiceCatalogTabs/><Card><CardHeader><CardTitle>Add Service</CardTitle></CardHeader><CardContent><form onSubmit={create} className="grid gap-3 md:grid-cols-2 xl:grid-cols-4"><select name="categoryId" required className="h-9 rounded border border-[#DCE6F2] bg-white px-3 text-[12px]"><option value="">Select category</option>{initialCategories.map(category=><option key={category.id} value={category.id}>{category.name}</option>)}</select><Input name="name" required maxLength={100} placeholder="Service name" /><Input name="imagePath" placeholder="/service-image.png" /><select name="unit" className="h-9 rounded border border-[#DCE6F2] bg-white px-3 text-[12px]"><option value="kg">Per kg</option><option value="item">Per item</option></select><Input name="regularPrice" required min={0} step="0.01" type="number" placeholder="Regular price" /><Input name="expressPrice" min={0} step="0.01" type="number" placeholder="Express price" /><Input name="turnaround" required placeholder="Turnaround, e.g. 1-2 Days" /><div className="flex gap-2"><Input name="displayOrder" required min={0} type="number" defaultValue={services.length+1} placeholder="Order" /><Button disabled={saving} className="bg-[#075DFF]">{saving?"Saving...":"Add Service"}</Button></div></form></CardContent></Card><Card><CardContent className="p-0"><Table><TableHeader><TableRow><TableHead>Service</TableHead><TableHead>Category</TableHead><TableHead>Unit</TableHead><TableHead>Price</TableHead><TableHead>Turnaround</TableHead><TableHead>Status</TableHead></TableRow></TableHeader><TableBody>{services.map(service=><TableRow key={service.id}><TableCell><div className="flex items-center gap-3"><CatalogImage path={service.imagePath} name={service.name}/><div><p className="font-medium">{service.name}</p><p className="text-[11px] text-[#52627A]">{service.slug}</p></div></div></TableCell><TableCell>{service.categoryName}</TableCell><TableCell>Per {service.unit}</TableCell><TableCell>₹{service.regularPrice}</TableCell><TableCell>{service.turnaround}</TableCell><TableCell><div className="flex items-center gap-2"><Switch checked={service.isActive} onCheckedChange={()=>toggle(service)}/><span className="text-[12px]">{service.isActive?"Shown":"Hidden"}</span></div></TableCell></TableRow>)}</TableBody></Table></CardContent></Card></div>;
}

export function ServicePricingAdmin({ initialServices }: { initialServices:CatalogService[] }) {
  const router=useRouter();const [services,setServices]=useState(initialServices);const [savingId,setSavingId]=useState("");
  function change(id:string,key:"regularPrice"|"expressPrice",value:string){setServices(current=>current.map(service=>service.id===id?{...service,[key]:value===""?null:Number(value)}:service));}
  async function save(service:CatalogService){setSavingId(service.id);const response=await fetch(`/api/admin/catalog-services/${service.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({regularPrice:service.regularPrice,expressPrice:service.expressPrice})});const data=await response.json() as {service?:CatalogService;message?:string};setSavingId("");if(!response.ok||!data.service){toast.error(data.message??"Unable to save price");return;}setServices(current=>current.map(item=>item.id===service.id?data.service!:item));toast.success("Price updated");router.refresh();}
  return <div className="space-y-3"><ServiceCatalogTabs/><Card><CardContent className="p-0"><Table><TableHeader><TableRow><TableHead>Service</TableHead><TableHead>Unit</TableHead><TableHead>Regular Price</TableHead><TableHead>Express Price</TableHead><TableHead className="text-right">Action</TableHead></TableRow></TableHeader><TableBody>{services.map(service=><TableRow key={service.id}><TableCell><p className="font-medium">{service.name}</p><p className="text-[11px] text-[#52627A]">{service.categoryName}</p></TableCell><TableCell>Per {service.unit}</TableCell><TableCell><Input aria-label={`${service.name} regular price`} type="number" min={0} step="0.01" value={service.regularPrice} onChange={event=>change(service.id,"regularPrice",event.target.value)} className="w-32" /></TableCell><TableCell><Input aria-label={`${service.name} express price`} type="number" min={0} step="0.01" value={service.expressPrice??""} onChange={event=>change(service.id,"expressPrice",event.target.value)} className="w-32" /></TableCell><TableCell className="text-right"><Button variant="outline" size="sm" disabled={savingId===service.id} onClick={()=>save(service)}>{savingId===service.id?"Saving...":"Save"}</Button></TableCell></TableRow>)}</TableBody></Table></CardContent></Card></div>;
}
